apiVersion: kettle.rossonet.net/v1
kind: KettleJob
metadata:
  name: job-example1
  namespace: test-namespace
spec:
  dir: "/examples" # The repository directory that contains the job, including the leading slash
  #file: "transformation_example" # If you are calling a local KJB file, this is the filename, including the path if it is not in the local directory
  #image: "rossonet/kettle-runner:latest" # docker image default is https://hub.docker.com/r/rossonet/kettle-runner
  level: "Debug" # The logging level (Basic, Detailed, Debug, Rowlevel, Error, Nothing)
  #listdir: "Y" # Lists the directories in the specified repository
  #listrep: "Y" # Lists the available repositories
  #listjob: "Y" # Lists the jobs in the specified repository directory
  #logfile: "file.log" # A local filename to write log output to
  #norep: "Y" # Prevents Pan from logging into a repository
  pass: "admin" # Repository password
  #param: ["parameter1=120","p2=ciao","parameter3=12"] # Set a named parameter in a name=value format. For example: -param:FOO=bar
  rep: "Repository repository-example1" # Enterprise or database repository name, if you are using one
  job: "job_example" # The name of the job (as it appears in the repository) to launch
  user: "admin" # Repository username
  #version: "Y" # Shows the version, revision, and build date
  #xmlRepository: ... # XML with repositories configuration
