apiVersion: kettle.rossonet.net/v1
kind: KettleIde
metadata:
  name: ide-example1
  namespace: test-namespace
spec:
  #image: "rossonet/kettle-vnc:latest" # docker image default is https://hub.docker.com/r/rossonet/kettle-vnc
  #host: "ide1.demo1.rossonet.com" # Ingress host
  path: "/ide1" # Ingress path
  servicePort: 443 # Ingress service port
  #xmlRepository: ... # XML with repositories configuration
