apiVersion: kettle.rossonet.net/v1
kind: KettleTransformation
metadata:
  name: trasformation-example1
  namespace: test-namespace
spec:
  dir: dir-value
  exprep: exprep-value
  file:	file-value
  #image: image-value
  level: level-value
  listdir: listdir-value 
  listrep: listrep-value
  listtrans: listtrans-value
  logfile: logfile-value
  norep: norep-value1
  pass: pass-value3
  param: ["pir1=0","par2=ciao","terzo=1"]
  rep: rep-value
  safemode: savemode-value2
  trans: trans-value2
  user:	user-value
  version: version-value

